[project]
name = "mojo-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NoRaincheck", email = "2498638+NoRaincheck@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
mojo-py = "mojo_py:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
